language: java

before_install:
  - wget http://mirrors.ae-online.de/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
  - tar xf apache-maven-3.5.4-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH

install: /bin/true

script: mvn clean install -Pci
