env:
  global:
    - CC_TEST_REPORTER_ID=7f97b09b52df4212c66f57cc09bdc7e3225161c2c6b149012a0b1335616b8831

language: java
jdk: openjdk10

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
  - unzip -qq apache-maven-3.5.4-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.4
  - export PATH=$M2_HOME/bin:$PATH
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install: /bin/true

script:
  - mvn clean install -Pci

after_success:
  - JACOCO_SOURCE_PATH=./src/main/java ./cc-test-reporter format-coverage ./target/coverage-reports/jacoco-ut.exec --input-type jacoco ./cc-test-reporter upload-coverage
  - bash <(curl -s https://codecov.io/bash)
